package rebuild

import (
	"encoding/json"
	"fmt"
	"os"
	"speaking_hearts/models"
	"time"
)

// AudioRebuilder handles the processing of recorded ceremony fragments.
// It is designed to rebuild the event timeline and export data into standard formats.
type AudioRebuilder struct {
	ActiveMetadata []MetadataFragment
}

// MetadataFragment matches the JSON structure generated by the storage engine.
// We expect this to contain both audio chunk references and their transcriptions.
type MetadataFragment struct {
	FragmentID int                 `json:"fragment_id"`
	Timestamp  time.Time           `json:"timestamp"`
	ChunkCount int                 `json:"chunk_count"`
	Chunks     []models.AudioChunk `json:"chunks"`
	// Note: We anticipate adding transcriptions to the metadata in future iterations.
	Transcriptions []models.ProcessedText `json:"transcriptions,omitempty"`
}

// NewAudioRebuilder creates a new instance of the rebuilder service.
func NewAudioRebuilder() *AudioRebuilder {
	return &AudioRebuilder{
		ActiveMetadata: make([]MetadataFragment, 0),
	}
}

// ProcessMetadata reads a metadata.json file and loads it into the rebuilder state.
func (r *AudioRebuilder) ProcessMetadata(metadataPath string) error {
	data, err := os.ReadFile(metadataPath)
	if err != nil {
		return fmt.Errorf("failed to read metadata file: %v", err)
	}

	var fragment MetadataFragment
	if err := json.Unmarshal(data, &fragment); err != nil {
		return fmt.Errorf("failed to parse metadata JSON: %v", err)
	}

	r.ActiveMetadata = append(r.ActiveMetadata, fragment)
	return nil
}

// ExportSRT generates a standard .srt subtitle file from the loaded transcriptions.
// It follows the format: Sequence, Timestamp (00:00:00,000), and Text.
func (r *AudioRebuilder) ExportSRT(outputPath string) error {
	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create SRT file: %v", err)
	}
	defer file.Close()

	seq := 1
	for _, fragment := range r.ActiveMetadata {
		// Use transcriptions if available, otherwise fallback to chunk timestamps (mock text)
		if len(fragment.Transcriptions) > 0 {
			for _, t := range fragment.Transcriptions {
				startTime := t.Timestamp.Format("15:04:05,000")
				endTime := t.Timestamp.Add(3 * time.Second).Format("15:04:05,000")

				fmt.Fprintf(file, "%d\n", seq)
				fmt.Fprintf(file, "%s --> %s\n", startTime, endTime)
				fmt.Fprintf(file, "%s\n\n", t.OriginalText)
				seq++
			}
		} else {
			// Fallback: If no transcriptions found, use chunks as placeholders
			for _, chunk := range fragment.Chunks {
				startTime := chunk.Timestamp.Format("15:04:05,000")
				endTime := chunk.Timestamp.Add(3 * time.Second).Format("15:04:05,000")

				fmt.Fprintf(file, "%d\n", seq)
				fmt.Fprintf(file, "%s --> %s\n", startTime, endTime)
				fmt.Fprintf(file, "[No Transcription Found for Chunk %s]\n\n", chunk.ID)
				seq++
			}
		}
	}

	return nil
}
